### ISSUE TITLE
[python] Generate GIF animations

### ISSUE THREAD

**Issue by sk33z3r** [sk33z3r/LooPyGen#3]
Need a way to differentiate between a GIF and a STATIC collection.

Most likely need imagemagick's convert, and will have to be very specific on how to organize the folder structure.

**Comment by Montspy** [comment]
I tried layering GIFs with `ffmpeg` and was successful:
```plaintext
ffmpeg -y -i dancer.gif -ignore_loop 0 -i sunset.gif -filter_complex "[0][1]overlay=format=auto:shortest=1,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" output.gif
```
Overlay filter docs: https://ffmpeg.org/ffmpeg-filters.html#overlay-1
![output](https://user-images.githubusercontent.com/2715455/159065520-8016db7c-2ce5-481c-8468-a1b84680fbf9.gif)

**Comment by Montspy** [comment]
For metadata generation of MP4s, we should generate a GIF out of it for `image` until explorer can handle non-images in `image`, or until we get marketplace

**Comment by Montspy** [comment]
Turns out MP4 (aka h.264) does not support alpha channels.
The recommended video format with alpha for web is WebM with VP9 codec. https://pixelbakery.co/recipes/list-of-video-image-formats-in-2021-supporting-alpha-channels
ffmpeg supports WebM with VP9. Example command for conversion with alpha channel:
```
ffmpeg -y -i sunset.gif  -c:v libvpx-vp9 -b:v 0 -crf 30 -row-mt 1 -pix_fmt yuva420p sunset.webm
```
`-c:v libvpx-vp9` forces the libvpx VP9 codec
`-b:v 0 -crf 30` forces variable bitrate with constant quality (good for final export) of 30 (0-63, lower is higher quality)
For intermediate steps, I'm thinking of using `-lossless` instead for speed and limit the quality loss with high layer numbers.
`-row-mt 1` is using row multithreading. To be confirmed if this speeds conversions up or not
`-pix_fmt yuva420p` uses YUVA (YUV+Alpha) 4:2:0 pixel format. 4:2:0 is the most used on the web
